version: "2.2"
services:
  web:
    image: gbglis/gbglis-web:${BRANCH_NAME}
    ports:
      - ${WEB_HOST_PORT}:80
    restart: always
  api:
    image: gbglis/gbglis-api:${BRANCH_NAME}
    environment:
      - ASPNETCORE_URLS=http://+:63195
    volumes:
      - /home/ironjab/shared/Images:/Images
    ports:
      - ${API_HOST_PORT}:63195
    restart: always
  identity:
    image: gbglis/gbglis-identity:${BRANCH_NAME}
    environment:
      - ASPNETCORE_URLS=http://+:44364
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - ${IDENTITY_HOST_PORT}:44364
    restart: always
