version: "2"
services:
  jenkins:
    image: gbglis/jenkins:lts-docker18.09.2
    volumes:
      - ./jenkins_home:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock
    ports:
      - "8320:8080"
      - "50000:50000"
    user: root
    restart: always
